name: flutter_logan
description: Flutter bindings for Logan on Android, iOS, and HarmonyOS.
version: 1.1.0
homepage: 'https://github.com/Meituan-Dianping/Logan/tree/master/Flutter'

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.meituan.flutter_logan
        pluginClass: FlutterLoganPlugin
      ios:
        pluginClass: FlutterLoganPlugin
      ohos:
        pluginClass: FlutterLoganPlugin
